# -*- coding: utf-8 -*-
"""통합크롤링.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2GPgLFBWkFTQkXiJ4J6xM44crw50wZX
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import urllib.parse
from datetime import datetime, timedelta

# --- 설정 및 입력 ---
keyword = input("조회할 키워드를 입력하세요: ")
days_limit = 3
limit_date = datetime.now() - timedelta(days=days_limit)

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
}

def get_bunjang_data(keyword):
    print(f"⚡ 번개장터 조회 시작...")
    items = []
    page = 0
    while True:
        url = f"https://api.bunjang.co.kr/api/1/find_v2.json?q={keyword}&order=date&n=100&page={page}"
        res = requests.get(url, headers=headers)
        data = res.json().get('list', [])
        if not data: break

        for item in data:
            updated_at = datetime.fromtimestamp(item.get('update_time'))
            if updated_at < limit_date: return items

            items.append({
                'platform': '번개장터',
                'pid': item.get('pid'),
                'name': item.get('name'),
                'price': item.get('price'),
                'status': '판매완료' if item.get('status') == '3' else '판매중',
                'description': f"지역: {item.get('location', '정보없음')}",
                'image_url': item.get('product_image'),
                'link': f"https://m.bunjang.co.kr/products/{item.get('pid')}",
                'date': updated_at.strftime('%Y-%m-%d %H:%M')
            })
        page += 1
        time.sleep(random.uniform(1.0, 1.5))
    return items

def get_joongna_web_data(keyword):
    print(f"📦 중고나라 웹 조회 시작...")
    encoded_keyword = urllib.parse.quote(keyword)
    items = []
    page = 1

    while True:
        url = f"https://web.joongna.com/search/{encoded_keyword}?page={page}"
        res = requests.get(url, headers=headers)
        if res.status_code != 200: break

        soup = BeautifulSoup(res.text, "html.parser")
        # 제품 카드 리스트 선택 (사용자님 코드 방식 유지)
        cards = soup.select('a[href^="/product/"]')
        if not cards: break

        for card in cards:
            # 1. PID 및 링크 추출
            link = "https://web.joongna.com" + card['href']
            pid = card['href'].split('/')[-1]

            # 2. 제목 추출
            title_tag = card.select_one('h2, .line-clamp-2')
            name = title_tag.text.strip() if title_tag else "제목없음"

            # 3. 가격 추출 (숫자만 추출)
            price_text = card.select_one('.font-bold, [class*="Price"]').text if card.select_one('.font-bold') else "0"
            price = "".join(filter(str.isdigit, price_text))

            # 4. 이미지 URL 추출
            img_tag = card.select_one('img')
            image_url = img_tag['src'] if img_tag else ""

            # 5. 시간 파싱 (3일 이내 필터링용)
            # 중고나라 웹은 'n시간 전', 'n일 전'으로 표시됨
            time_text = card.select_one('span:contains("전"), .text-sm').text if card.select_one('span:contains("전")') else ""

            # 간단한 날짜 필터링 (예: '4일 전'이면 중단)
            if '일 전' in time_text:
                days_ago = int("".join(filter(str.isdigit, time_text)))
                if days_ago > days_limit:
                    return items

            items.append({
                'platform': '중고나라',
                'pid': pid,
                'name': name,
                'price': int(price) if price else 0,
                'status': '판매중', # 리스트에선 상세 확인 어려우므로 기본값
                'description': '상세보기 참조',
                'image_url': image_url,
                'link': link,
                'date': time_text
            })

        print(f"중고나라 {page}페이지 완료...")
        page += 1
        time.sleep(random.uniform(1.5, 2.5)) # robots.txt 준수 및 차단 방지
        if page > 10: break # 안전장치

    return items

# --- 실행 및 합치기 ---
bj_data = get_bunjang_data(keyword)
jn_data = get_joongna_web_data(keyword)

df = pd.DataFrame(bj_data + jn_data)

# 결과 출력
print(f"\n✅ 총 {len(df)}개 매물 수집 완료!")
display(df.head())

# CSV 저장
now = datetime.now().strftime("%Y%m%d_%H%M")
df.to_csv(f"통합조회_{keyword}_{now}.csv", index=False, encoding='utf-8-sig')
