# -*- coding: utf-8 -*-
"""통합크롤링.ipynb

Automatically generated by Colab.
4
Original file is located at
    https://colab.research.google.com/drive/1D2GPgLFBWkFTQkXiJ4J6xM44crw50wZX
"""

import requests
import pandas as pd
import time
import random
import urllib.parse
import json
import re
from datetime import datetime, timedelta
from pathlib import Path

# --- 설정 및 입력 ---
keyword_file = Path(__file__).with_name("keyword_list.csv")
keyword_df = pd.read_csv(keyword_file, encoding='utf-8-sig')
keyword_column = 'keyword' if 'keyword' in keyword_df.columns else keyword_df.columns[0]
keywords = keyword_df[keyword_column].dropna().astype(str).str.strip()
keywords = [keyword for keyword in keywords if keyword]

if not keywords:
    raise ValueError(f"{keyword_file.name} 파일에 조회할 키워드가 없습니다.")

days_limit = 3
limit_date = datetime.now() - timedelta(days=days_limit)

result_columns = [
    'platform',
    'pid',
    'name',
    'price',
    'status',
    'description',
    'image_url',
    'link',
    'date',
]

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
}

def safe_filename(value):
    return re.sub(r'[\\/:*?"<>|]+', '_', value).strip()

def get_bunjang_status(status):
    status_map = {
        '0': '판매중',
        '1': '예약중',
        '2': '거래중',
        '3': '판매완료',
    }
    status = str(status)
    return status_map.get(status, f"상태코드:{status}")

def decode_joongna_text(value):
    try:
        return json.loads(f'"{value}"')
    except Exception:
        return value

def get_joongna_status(state):
    status_map = {
        0: "판매중",
        1: "예약중",
        3: "거래완료",
    }
    return status_map.get(state, f"상태코드:{state}")

def parse_joongna_search_items(html):
    pattern = re.compile(
        r'\{\\"seq\\":(?P<pid>\d+).*?'
        r'\\"price\\":(?P<price>\d+).*?'
        r'\\"url\\":\\"(?P<image_url>.*?)\\".*?'
        r'\\"title\\":\\"(?P<name>.*?)\\",'
        r'\\"state\\":(?P<state>\d+),'
        r'\\"sortDate\\":\\"(?P<date>.*?)\\"',
        re.S
    )

    items = []
    for match in pattern.finditer(html):
        items.append({
            "pid": match.group("pid"),
            "name": decode_joongna_text(match.group("name")),
            "price": int(match.group("price")),
            "status": get_joongna_status(int(match.group("state"))),
            "image_url": decode_joongna_text(match.group("image_url")),
            "date": match.group("date"),
        })

    return items

def get_bunjang_data(keyword):
    print(f"⚡ 번개장터 조회 시작...")
    items = []
    page = 0
    while True:
        encoded_keyword = urllib.parse.quote(keyword)
        url = f"https://api.bunjang.co.kr/api/1/find_v2.json?q={encoded_keyword}&order=date&n=100&page={page}"
        res = requests.get(url, headers=headers, timeout=10)
        data = res.json().get('list', [])
        if not data: break

        for item in data:
            updated_at = datetime.fromtimestamp(item.get('update_time'))
            if updated_at < limit_date: return items

            items.append({
                'platform': '번개장터',
                'pid': item.get('pid'),
                'name': item.get('name'),
                'price': item.get('price'),
                'status': get_bunjang_status(item.get('status')),
                'description': '',
                'image_url': item.get('product_image'),
                'link': f"https://m.bunjang.co.kr/products/{item.get('pid')}",
                'date': updated_at.strftime('%Y-%m-%d %H:%M')
            })
        page += 1
        time.sleep(random.uniform(1.0, 1.5))
    return items

def get_joongna_web_data(keyword):
    print(f"📦 중고나라 웹 조회 시작...")
    encoded_keyword = urllib.parse.quote(keyword)
    items = []
    page = 1

    while True:
        url = f"https://web.joongna.com/search/{encoded_keyword}?page={page}&excludeSoldOutProductYn=N"
        res = requests.get(url, headers=headers, timeout=10)
        if res.status_code != 200: break

        search_items = parse_joongna_search_items(res.text)
        if not search_items: break

        for item in search_items:
            item_date = datetime.strptime(item["date"], '%Y-%m-%d %H:%M:%S')

            if item_date and item_date < limit_date:
                continue

            items.append({
                'platform': '중고나라',
                'pid': item["pid"],
                'name': item["name"],
                'price': item["price"],
                'status': item["status"],
                'description': '',
                'image_url': item["image_url"],
                'link': f"https://web.joongna.com/product/{item['pid']}",
                'date': item_date.strftime('%Y-%m-%d %H:%M') if item_date else ""
            })

        print(f"중고나라 {page}페이지 완료...")
        page += 1
        time.sleep(random.uniform(1.5, 2.5)) # robots.txt 준수 및 차단 방지
        if page > 10: break # 안전장치

    return items

# --- 실행 및 합치기 ---
now = datetime.now().strftime("%Y%m%d_%H%M")
all_dfs = []

print("\n조회 키워드 목록")
for idx, keyword in enumerate(keywords, start=1):
    print(f"{idx}. {keyword}")

for keyword in keywords:
    print(f"\n🔎 [{keyword}] 조회 시작")
    bj_data = get_bunjang_data(keyword)
    jn_data = get_joongna_web_data(keyword)

    df = pd.DataFrame(bj_data + jn_data, columns=result_columns)
    df.insert(0, 'keyword', keyword)
    all_dfs.append(df)

    print(f"✅ [{keyword}] 총 {len(df)}개 매물 수집 완료!")
    print(df.head())

    df.to_csv(f"통합조회_{safe_filename(keyword)}_{now}.csv", index=False, encoding='utf-8-sig')

if all_dfs:
    total_df = pd.concat(all_dfs, ignore_index=True)
    total_df.to_csv(f"통합조회_전체_{now}.csv", index=False, encoding='utf-8-sig')
    print(f"\n✅ 전체 키워드 총 {len(total_df)}개 매물 수집 완료!")
